<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Bahan_masuk extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Bahan_masuk_model');
    } 

    /*
     * Listing of bahan_masuk
     */
    function index()
    {
        $data['bahan_masuk'] = $this->Bahan_masuk_model->get_all_bahan_masuk();

        $data['_view'] = 'bahan_masuk/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new bahan_masuk
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('msk_bahan','Msk Bahan','integer');
		$this->form_validation->set_rules('msk_olah_rusak','Msk Olah Rusak','integer');
		$this->form_validation->set_rules('msk_jahit_rusak','Msk Jahit Rusak','integer');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'brg_id' => $this->input->post('brg_id'),
				'msk_bahan' => $this->input->post('msk_bahan'),
				'msk_olah_rusak' => $this->input->post('msk_olah_rusak'),
				'msk_jahit_rusak' => $this->input->post('msk_jahit_rusak'),
            );

            $bahan_masuk_id = $this->Bahan_masuk_model->add_bahan_masuk($params);
            redirect('bahan_masuk/index');
        }
        else
        {
            $this->load->model('Bahan_model');
            $data['all_bahan'] = $this->Bahan_model->get_all_bahan();

            $data['_view'] = 'bahan_masuk/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a bahan_masuk
     */
    function edit($msk_id)
    {
        // check if the bahan_masuk exists before trying to edit it
        $data['bahan_masuk'] = $this->Bahan_masuk_model->get_bahan_masuk($msk_id);

        if (isset($data['bahan_masuk']['msk_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('msk_bahan','Msk Bahan','integer');
			$this->form_validation->set_rules('msk_olah_rusak','Msk Olah Rusak','integer');
			$this->form_validation->set_rules('msk_jahit_rusak','Msk Jahit Rusak','integer');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'brg_id' => $this->input->post('brg_id'),
					'msk_bahan' => $this->input->post('msk_bahan'),
					'msk_olah_rusak' => $this->input->post('msk_olah_rusak'),
					'msk_jahit_rusak' => $this->input->post('msk_jahit_rusak'),
                );

                $this->Bahan_masuk_model->update_bahan_masuk($msk_id, $params);
                redirect('bahan_masuk/index');
            }
            else
            {
                $this->load->model('Bahan_model');
                $data['all_bahan'] = $this->Bahan_model->get_all_bahan();

                $data['_view'] = 'bahan_masuk/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The bahan_masuk you are trying to edit does not exist.');
    } 

    /*
     * Deleting bahan_masuk
     */
    function remove($msk_id)
    {
        $bahan_masuk = $this->Bahan_masuk_model->get_bahan_masuk($msk_id);

        // check if the bahan_masuk exists before trying to delete it
        if (isset($bahan_masuk['msk_id']))
        {
            $this->Bahan_masuk_model->delete_bahan_masuk($msk_id);
            redirect('bahan_masuk/index');
        }
        else
            show_error('The bahan_masuk you are trying to delete does not exist.');
    }
    
}
