<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Bahan_keluar extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Bahan_keluar_model');
    } 

    /*
     * Listing of bahan_keluar
     */
    function index()
    {
        $data['bahan_keluar'] = $this->Bahan_keluar_model->get_all_bahan_keluar();

        $data['_view'] = 'bahan_keluar/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new bahan_keluar
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('klr_jmlah','Klr Jmlah','integer');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'brg_id' => $this->input->post('brg_id'),
				'rsl_id' => $this->input->post('rsl_id'),
				'klr_jmlah' => $this->input->post('klr_jmlah'),
            );

            $bahan_keluar_id = $this->Bahan_keluar_model->add_bahan_keluar($params);
            redirect('bahan_keluar/index');
        }
        else
        {
            $this->load->model('Bahan_model');
            $data['all_bahan'] = $this->Bahan_model->get_all_bahan();

			$this->load->model('Reseller_model');
			$data['all_reseller'] = $this->Reseller_model->get_all_reseller();

            $data['_view'] = 'bahan_keluar/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a bahan_keluar
     */
    function edit($klr_id)
    {
        // check if the bahan_keluar exists before trying to edit it
        $data['bahan_keluar'] = $this->Bahan_keluar_model->get_bahan_keluar($klr_id);

        if (isset($data['bahan_keluar']['klr_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('klr_jmlah','Klr Jmlah','integer');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'brg_id' => $this->input->post('brg_id'),
					'rsl_id' => $this->input->post('rsl_id'),
					'klr_jmlah' => $this->input->post('klr_jmlah'),
                );

                $this->Bahan_keluar_model->update_bahan_keluar($klr_id, $params);
                redirect('bahan_keluar/index');
            }
            else
            {
                $this->load->model('Bahan_model');
                $data['all_bahan'] = $this->Bahan_model->get_all_bahan();

				$this->load->model('Reseller_model');
				$data['all_reseller'] = $this->Reseller_model->get_all_reseller();

                $data['_view'] = 'bahan_keluar/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The bahan_keluar you are trying to edit does not exist.');
    } 

    /*
     * Deleting bahan_keluar
     */
    function remove($klr_id)
    {
        $bahan_keluar = $this->Bahan_keluar_model->get_bahan_keluar($klr_id);

        // check if the bahan_keluar exists before trying to delete it
        if (isset($bahan_keluar['klr_id']))
        {
            $this->Bahan_keluar_model->delete_bahan_keluar($klr_id);
            redirect('bahan_keluar/index');
        }
        else
            show_error('The bahan_keluar you are trying to delete does not exist.');
    }
    
}
