<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Bahan_retur extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Bahan_retur_model');
    } 

    /*
     * Listing of bahan_retur
     */
    function index()
    {
        $data['bahan_retur'] = $this->Bahan_retur_model->get_all_bahan_retur();

        $data['_view'] = 'bahan_retur/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new bahan_retur
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('rtr_jmlah','Rtr Jmlah','integer');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'brg_id' => $this->input->post('brg_id'),
				'rsl_id' => $this->input->post('rsl_id'),
				'rtr_jmlah' => $this->input->post('rtr_jmlah'),
                'created_at' => date('Y-m-d H:i:s'),
            );

            $bahan_retur_id = $this->Bahan_retur_model->add_bahan_retur($params);
            redirect('bahan_retur/index');
        }
        else
        {
            $this->load->model('Bahan_model');
            $data['all_bahan'] = $this->Bahan_model->get_all_bahan();

			$this->load->model('Reseller_model');
			$data['all_reseller'] = $this->Reseller_model->get_all_reseller();

            $data['_view'] = 'bahan_retur/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a bahan_retur
     */
    function edit($rtr_id)
    {
        // check if the bahan_retur exists before trying to edit it
        $data['bahan_retur'] = $this->Bahan_retur_model->get_bahan_retur($rtr_id);

        if (isset($data['bahan_retur']['rtr_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('rtr_jmlah','Rtr Jmlah','integer');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'brg_id' => $this->input->post('brg_id'),
					'rsl_id' => $this->input->post('rsl_id'),
					'rtr_jmlah' => $this->input->post('rtr_jmlah'),
                );

                $this->Bahan_retur_model->update_bahan_retur($rtr_id, $params);
                redirect('bahan_retur/index');
            }
            else
            {
                $this->load->model('Bahan_model');
                $data['all_bahan'] = $this->Bahan_model->get_all_bahan();

				$this->load->model('Reseller_model');
				$data['all_reseller'] = $this->Reseller_model->get_all_reseller();

                $data['_view'] = 'bahan_retur/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The bahan_retur you are trying to edit does not exist.');
    } 

    /*
     * Deleting bahan_retur
     */
    function remove($rtr_id)
    {
        $bahan_retur = $this->Bahan_retur_model->get_bahan_retur($rtr_id);

        // check if the bahan_retur exists before trying to delete it
        if (isset($bahan_retur['rtr_id']))
        {
            $this->Bahan_retur_model->delete_bahan_retur($rtr_id);
            redirect('bahan_retur/index');
        }
        else
            show_error('The bahan_retur you are trying to delete does not exist.');
    }
    
}
