<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Bahan extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Bahan_model');
    } 

    /*
     * Listing of bahan
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('bahan/index?');
        $config['total_rows'] = $this->Bahan_model->get_all_bahan_count();
        $this->pagination->initialize($config);

        $data['bahan'] = $this->Bahan_model->get_all_bahan($params);

        $data['_view'] = 'bahan/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new bahan
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'brg_status' => $this->input->post('brg_status'),
				'brg_fast' => $this->input->post('brg_fast'),
				'brg_paloma' => $this->input->post('brg_paloma'),
				'brg_hrg_pokok' => $this->input->post('brg_hrg_pokok'),
				'brg_hrg_jual' => $this->input->post('brg_hrg_jual'),
				'brg_kode' => $this->input->post('brg_kode'),
            );

            $bahan_id = $this->Bahan_model->add_bahan($params);
            redirect('bahan/index');
        }
        else
        {
            $data['_view'] = 'bahan/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a bahan
     */
    function edit($brg_id)
    {
        // check if the bahan exists before trying to edit it
        $data['bahan'] = $this->Bahan_model->get_bahan($brg_id);

        if (isset($data['bahan']['brg_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'brg_status' => $this->input->post('brg_status'),
					'brg_fast' => $this->input->post('brg_fast'),
					'brg_paloma' => $this->input->post('brg_paloma'),
					'brg_hrg_pokok' => $this->input->post('brg_hrg_pokok'),
					'brg_hrg_jual' => $this->input->post('brg_hrg_jual'),
					'brg_kode' => $this->input->post('brg_kode'),
                );

                $this->Bahan_model->update_bahan($brg_id, $params);
                redirect('bahan/index');
            }
            else
            {
                $data['_view'] = 'bahan/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('Data yang ingin diubah tidak ditemukan.');
    } 

    /*
     * Deleting bahan
     */
    function remove($brg_id)
    {
        $bahan = $this->Bahan_model->get_bahan($brg_id);

        // check if the bahan exists before trying to delete it
        if (isset($bahan['brg_id']))
        {
            $this->Bahan_model->delete_bahan($brg_id);
            redirect('bahan/index');
        }
        else
            show_error('Data yang ingin dihapus tidak ditemukan');
    }
    
}
