<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Barang_retur extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Barang_retur_model');
    } 

    /*
     * Listing of barang_retur
     */
    function index()
    {
        $data['barang_retur'] = $this->Barang_retur_model->get_all_barang_retur();
        
        $data['_view'] = 'barang_retur/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new barang_retur
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('rtr_jmlah','Rtr Jmlah','integer');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'brg_id' => $this->input->post('brg_id'),
				'rsl_id' => $this->input->post('rsl_id'),
				'rtr_jmlah' => $this->input->post('rtr_jmlah'),
            );
            
            $barang_retur_id = $this->Barang_retur_model->add_barang_retur($params);
            redirect('barang_retur/index');
        }
        else
        {
			$this->load->model('Barang_model');
			$data['all_barang'] = $this->Barang_model->get_all_barang();

			$this->load->model('Reseller_model');
			$data['all_reseller'] = $this->Reseller_model->get_all_reseller();
            
            $data['_view'] = 'barang_retur/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a barang_retur
     */
    function edit($rtr_id)
    {   
        // check if the barang_retur exists before trying to edit it
        $data['barang_retur'] = $this->Barang_retur_model->get_barang_retur($rtr_id);
        
        if(isset($data['barang_retur']['rtr_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('rtr_jmlah','Rtr Jmlah','integer');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'brg_id' => $this->input->post('brg_id'),
					'rsl_id' => $this->input->post('rsl_id'),
					'rtr_jmlah' => $this->input->post('rtr_jmlah'),
                );

                $this->Barang_retur_model->update_barang_retur($rtr_id,$params);            
                redirect('barang_retur/index');
            }
            else
            {
				$this->load->model('Barang_model');
				$data['all_barang'] = $this->Barang_model->get_all_barang();

				$this->load->model('Reseller_model');
				$data['all_reseller'] = $this->Reseller_model->get_all_reseller();

                $data['_view'] = 'barang_retur/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The barang_retur you are trying to edit does not exist.');
    } 

    /*
     * Deleting barang_retur
     */
    function remove($rtr_id)
    {
        $barang_retur = $this->Barang_retur_model->get_barang_retur($rtr_id);

        // check if the barang_retur exists before trying to delete it
        if(isset($barang_retur['rtr_id']))
        {
            $this->Barang_retur_model->delete_barang_retur($rtr_id);
            redirect('barang_retur/index');
        }
        else
            show_error('The barang_retur you are trying to delete does not exist.');
    }
    
}
