<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Barang extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Barang_model');
    } 

    /*
     * Listing of barang
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('barang/index?');
        $config['total_rows'] = $this->Barang_model->get_all_barang_count();
        $this->pagination->initialize($config);

        $data['barang'] = $this->Barang_model->get_all_barang($params);
        
        $data['_view'] = 'barang/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new barang
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'brg_status' => $this->input->post('brg_status'),
				'brg_fast' => $this->input->post('brg_fast'),
				'brg_paloma' => $this->input->post('brg_paloma'),
				'brg_hrg_pokok' => $this->input->post('brg_hrg_pokok'),
				'brg_hrg_jual' => $this->input->post('brg_hrg_jual'),
				'brg_kode' => $this->input->post('brg_kode'),
            );
            
            $barang_id = $this->Barang_model->add_barang($params);
            redirect('barang/index');
        }
        else
        {            
            $data['_view'] = 'barang/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a barang
     */
    function edit($brg_id)
    {   
        // check if the barang exists before trying to edit it
        $data['barang'] = $this->Barang_model->get_barang($brg_id);
        
        if(isset($data['barang']['brg_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'brg_status' => $this->input->post('brg_status'),
					'brg_fast' => $this->input->post('brg_fast'),
					'brg_paloma' => $this->input->post('brg_paloma'),
					'brg_hrg_pokok' => $this->input->post('brg_hrg_pokok'),
					'brg_hrg_jual' => $this->input->post('brg_hrg_jual'),
					'brg_kode' => $this->input->post('brg_kode'),
                );

                $this->Barang_model->update_barang($brg_id,$params);            
                redirect('barang/index');
            }
            else
            {
                $data['_view'] = 'barang/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('Data yang ingin diubah tidak ditemukan.');
    } 

    /*
     * Deleting barang
     */
    function remove($brg_id)
    {
        $barang = $this->Barang_model->get_barang($brg_id);

        // check if the barang exists before trying to delete it
        if(isset($barang['brg_id']))
        {
            $this->Barang_model->delete_barang($brg_id);
            redirect('barang/index');
        }
        else
            show_error('Data yang ingin dihapus tidak ditemukan');
    }
    
}
