<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Barang_masuk extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Barang_masuk_model');
    } 

    /*
     * Listing of barang_masuk
     */
    function index()
    {
        $data['barang_masuk'] = $this->Barang_masuk_model->get_all_barang_masuk();
        
        $data['_view'] = 'barang_masuk/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new barang_masuk
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('msk_bahan','Msk Bahan','integer');
		$this->form_validation->set_rules('msk_olah_rusak','Msk Olah Rusak','integer');
		$this->form_validation->set_rules('msk_jahit_rusak','Msk Jahit Rusak','integer');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'brg_id' => $this->input->post('brg_id'),
				'msk_bahan' => $this->input->post('msk_bahan'),
				'msk_olah_rusak' => $this->input->post('msk_olah_rusak'),
				'msk_jahit_rusak' => $this->input->post('msk_jahit_rusak'),
            );
            
            $barang_masuk_id = $this->Barang_masuk_model->add_barang_masuk($params);
            redirect('barang_masuk/index');
        }
        else
        {
			$this->load->model('Barang_model');
			$data['all_barang'] = $this->Barang_model->get_all_barang();
            
            $data['_view'] = 'barang_masuk/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a barang_masuk
     */
    function edit($msk_id)
    {   
        // check if the barang_masuk exists before trying to edit it
        $data['barang_masuk'] = $this->Barang_masuk_model->get_barang_masuk($msk_id);
        
        if(isset($data['barang_masuk']['msk_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('msk_bahan','Msk Bahan','integer');
			$this->form_validation->set_rules('msk_olah_rusak','Msk Olah Rusak','integer');
			$this->form_validation->set_rules('msk_jahit_rusak','Msk Jahit Rusak','integer');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'brg_id' => $this->input->post('brg_id'),
					'msk_bahan' => $this->input->post('msk_bahan'),
					'msk_olah_rusak' => $this->input->post('msk_olah_rusak'),
					'msk_jahit_rusak' => $this->input->post('msk_jahit_rusak'),
                );

                $this->Barang_masuk_model->update_barang_masuk($msk_id,$params);            
                redirect('barang_masuk/index');
            }
            else
            {
				$this->load->model('Barang_model');
				$data['all_barang'] = $this->Barang_model->get_all_barang();

                $data['_view'] = 'barang_masuk/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The barang_masuk you are trying to edit does not exist.');
    } 

    /*
     * Deleting barang_masuk
     */
    function remove($msk_id)
    {
        $barang_masuk = $this->Barang_masuk_model->get_barang_masuk($msk_id);

        // check if the barang_masuk exists before trying to delete it
        if(isset($barang_masuk['msk_id']))
        {
            $this->Barang_masuk_model->delete_barang_masuk($msk_id);
            redirect('barang_masuk/index');
        }
        else
            show_error('The barang_masuk you are trying to delete does not exist.');
    }
    
}
