<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Barang_keluar extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Barang_keluar_model');
    } 

    /*
     * Listing of barang_keluar
     */
    function index()
    {
        $data['barang_keluar'] = $this->Barang_keluar_model->get_all_barang_keluar();
        
        $data['_view'] = 'barang_keluar/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new barang_keluar
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('klr_jmlah','Klr Jmlah','integer');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'brg_id' => $this->input->post('brg_id'),
				'rsl_id' => $this->input->post('rsl_id'),
				'klr_jmlah' => $this->input->post('klr_jmlah'),
            );
            
            $barang_keluar_id = $this->Barang_keluar_model->add_barang_keluar($params);
            redirect('barang_keluar/index');
        }
        else
        {
			$this->load->model('Barang_model');
			$data['all_barang'] = $this->Barang_model->get_all_barang();

			$this->load->model('Reseller_model');
			$data['all_reseller'] = $this->Reseller_model->get_all_reseller();
            
            $data['_view'] = 'barang_keluar/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a barang_keluar
     */
    function edit($klr_id)
    {   
        // check if the barang_keluar exists before trying to edit it
        $data['barang_keluar'] = $this->Barang_keluar_model->get_barang_keluar($klr_id);
        
        if(isset($data['barang_keluar']['klr_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('klr_jmlah','Klr Jmlah','integer');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'brg_id' => $this->input->post('brg_id'),
					'rsl_id' => $this->input->post('rsl_id'),
					'klr_jmlah' => $this->input->post('klr_jmlah'),
                );

                $this->Barang_keluar_model->update_barang_keluar($klr_id,$params);            
                redirect('barang_keluar/index');
            }
            else
            {
				$this->load->model('Barang_model');
				$data['all_barang'] = $this->Barang_model->get_all_barang();

				$this->load->model('Reseller_model');
				$data['all_reseller'] = $this->Reseller_model->get_all_reseller();

                $data['_view'] = 'barang_keluar/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The barang_keluar you are trying to edit does not exist.');
    } 

    /*
     * Deleting barang_keluar
     */
    function remove($klr_id)
    {
        $barang_keluar = $this->Barang_keluar_model->get_barang_keluar($klr_id);

        // check if the barang_keluar exists before trying to delete it
        if(isset($barang_keluar['klr_id']))
        {
            $this->Barang_keluar_model->delete_barang_keluar($klr_id);
            redirect('barang_keluar/index');
        }
        else
            show_error('The barang_keluar you are trying to delete does not exist.');
    }
    
}
