<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Reseller extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Reseller_model');
    } 

    /*
     * Listing of reseller
     */
    function index()
    {
        $data['reseller'] = $this->Reseller_model->get_all_reseller();
        
        $data['_view'] = 'reseller/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new reseller
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('rsl_email','E-mail','valid_email');
		$this->form_validation->set_rules('rsl_nama','Nama','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'rsl_nama' => $this->input->post('rsl_nama'),
				'rsl_kontak' => $this->input->post('rsl_kontak'),
				'rsl_email' => $this->input->post('rsl_email'),
            );
            
            $reseller_id = $this->Reseller_model->add_reseller($params);
            redirect('reseller/index');
        }
        else
        {            
            $data['_view'] = 'reseller/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a reseller
     */
    function edit($rsl_id)
    {   
        // check if the reseller exists before trying to edit it
        $data['reseller'] = $this->Reseller_model->get_reseller($rsl_id);
        
        if(isset($data['reseller']['rsl_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('rsl_email','Rsl Email','valid_email');
			$this->form_validation->set_rules('rsl_nama','Rsl Nama','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'rsl_nama' => $this->input->post('rsl_nama'),
					'rsl_kontak' => $this->input->post('rsl_kontak'),
					'rsl_email' => $this->input->post('rsl_email'),
                );

                $this->Reseller_model->update_reseller($rsl_id,$params);            
                redirect('reseller/index');
            }
            else
            {
                $data['_view'] = 'reseller/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('Data yang ingin diubah tidak ditemukan.');
    } 

    /*
     * Deleting reseller
     */
    function remove($rsl_id)
    {
        $reseller = $this->Reseller_model->get_reseller($rsl_id);

        // check if the reseller exists before trying to delete it
        if(isset($reseller['rsl_id']))
        {
            $this->Reseller_model->delete_reseller($rsl_id);
            redirect('reseller/index');
        }
        else
            show_error('Data yang ingin dihapus tidak ditemukan.');
    }
    
}
