<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Bahan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get bahan by brg_id
     */
    function get_bahan($brg_id)
    {
        return $this->db->get_where('bahan', array('brg_id' => $brg_id))->row_array();
    }
    
    /*
     * Get all bahan count
     */
    function get_all_bahan_count()
    {
        $this->db->from('bahan');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all bahan
     */
    function get_all_bahan($params = array())
    {
        $this->db->order_by('brg_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('bahan')->result_array();
    }
        
    /*
     * function to add new bahan
     */
    function add_bahan($params)
    {
        $this->db->insert('bahan', $params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update bahan
     */
    function update_bahan($brg_id, $params)
    {
        $this->db->where('brg_id',$brg_id);
        return $this->db->update('bahan', $params);
    }
    
    /*
     * function to delete bahan
     */
    function delete_bahan($brg_id)
    {
        return $this->db->delete('bahan', array('brg_id' => $brg_id));
    }
}
