<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Bahan_keluar_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get bahan_keluar by klr_id
     */
    function get_bahan_keluar($klr_id)
    {
        return $this->db->get_where('bahan_keluar', array('klr_id' => $klr_id))->row_array();
    }
        
    /*
     * Get all bahan_keluar
     */
    function get_all_bahan_keluar()
    {
        $this->db->order_by('klr_id', 'desc');
        return $this->db->get('bahan_keluar')->result_array();
    }
        
    /*
     * function to add new bahan_keluar
     */
    function add_bahan_keluar($params)
    {
        $this->db->insert('bahan_keluar', $params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update bahan_keluar
     */
    function update_bahan_keluar($klr_id, $params)
    {
        $this->db->where('klr_id',$klr_id);
        return $this->db->update('bahan_keluar', $params);
    }
    
    /*
     * function to delete bahan_keluar
     */
    function delete_bahan_keluar($klr_id)
    {
        return $this->db->delete('bahan_keluar', array('klr_id' => $klr_id));
    }
}
