<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Bahan_masuk_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get bahan_masuk by msk_id
     */
    function get_bahan_masuk($msk_id)
    {
        return $this->db->get_where('bahan_masuk', array('msk_id' => $msk_id))->row_array();
    }
        
    /*
     * Get all bahan_masuk
     */
    function get_all_bahan_masuk()
    {
        $this->db->order_by('msk_id', 'desc');
        return $this->db->get('bahan_masuk')->result_array();
    }
        
    /*
     * function to add new bahan_masuk
     */
    function add_bahan_masuk($params)
    {
        $this->db->insert('bahan_masuk', $params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update bahan_masuk
     */
    function update_bahan_masuk($msk_id, $params)
    {
        $this->db->where('msk_id',$msk_id);
        return $this->db->update('bahan_masuk', $params);
    }
    
    /*
     * function to delete bahan_masuk
     */
    function delete_bahan_masuk($msk_id)
    {
        return $this->db->delete('bahan_masuk', array('msk_id' => $msk_id));
    }
}
