<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Barang_keluar_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get barang_keluar by klr_id
     */
    function get_barang_keluar($klr_id)
    {
        return $this->db->get_where('barang_keluar',array('klr_id'=>$klr_id))->row_array();
    }
        
    /*
     * Get all barang_keluar
     */
    function get_all_barang_keluar()
    {
        $this->db->order_by('klr_id', 'desc');
        return $this->db->get('barang_keluar')->result_array();
    }
        
    /*
     * function to add new barang_keluar
     */
    function add_barang_keluar($params)
    {
        $this->db->insert('barang_keluar',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update barang_keluar
     */
    function update_barang_keluar($klr_id,$params)
    {
        $this->db->where('klr_id',$klr_id);
        return $this->db->update('barang_keluar',$params);
    }
    
    /*
     * function to delete barang_keluar
     */
    function delete_barang_keluar($klr_id)
    {
        return $this->db->delete('barang_keluar',array('klr_id'=>$klr_id));
    }
}
