<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Barang_masuk_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get barang_masuk by msk_id
     */
    function get_barang_masuk($msk_id)
    {
        return $this->db->get_where('barang_masuk',array('msk_id'=>$msk_id))->row_array();
    }
        
    /*
     * Get all barang_masuk
     */
    function get_all_barang_masuk()
    {
        $this->db->order_by('msk_id', 'desc');
        return $this->db->get('barang_masuk')->result_array();
    }
        
    /*
     * function to add new barang_masuk
     */
    function add_barang_masuk($params)
    {
        $this->db->insert('barang_masuk',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update barang_masuk
     */
    function update_barang_masuk($msk_id,$params)
    {
        $this->db->where('msk_id',$msk_id);
        return $this->db->update('barang_masuk',$params);
    }
    
    /*
     * function to delete barang_masuk
     */
    function delete_barang_masuk($msk_id)
    {
        return $this->db->delete('barang_masuk',array('msk_id'=>$msk_id));
    }
}
