<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Barang_retur_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get barang_retur by rtr_id
     */
    function get_barang_retur($rtr_id)
    {
        return $this->db->get_where('barang_retur',array('rtr_id'=>$rtr_id))->row_array();
    }
        
    /*
     * Get all barang_retur
     */
    function get_all_barang_retur()
    {
        $this->db->order_by('rtr_id', 'desc');
        return $this->db->get('barang_retur')->result_array();
    }
        
    /*
     * function to add new barang_retur
     */
    function add_barang_retur($params)
    {
        $this->db->insert('barang_retur',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update barang_retur
     */
    function update_barang_retur($rtr_id,$params)
    {
        $this->db->where('rtr_id',$rtr_id);
        return $this->db->update('barang_retur',$params);
    }
    
    /*
     * function to delete barang_retur
     */
    function delete_barang_retur($rtr_id)
    {
        return $this->db->delete('barang_retur',array('rtr_id'=>$rtr_id));
    }
}
