<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Barang_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get barang by brg_id
     */
    function get_barang($brg_id)
    {
        return $this->db->get_where('barang',array('brg_id'=>$brg_id))->row_array();
    }
    
    /*
     * Get all barang count
     */
    function get_all_barang_count()
    {
        $this->db->from('barang');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all barang
     */
    function get_all_barang($params = array())
    {
        $this->db->order_by('brg_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('barang')->result_array();
    }
        
    /*
     * function to add new barang
     */
    function add_barang($params)
    {
        $this->db->insert('barang',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update barang
     */
    function update_barang($brg_id,$params)
    {
        $this->db->where('brg_id',$brg_id);
        return $this->db->update('barang',$params);
    }
    
    /*
     * function to delete barang
     */
    function delete_barang($brg_id)
    {
        return $this->db->delete('barang',array('brg_id'=>$brg_id));
    }
}
